language: node_js
sudo: required
node_js: --lts

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "fizzybreezy"
  - git config user.email "shenxingjian@live.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy 
